// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator.Cli.Templates
{
    using System.Collections.Generic;
    using Generator.Cli.Metamodel;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Jack\repo\CodeGenerator\Generator.Cli\Templates\EntityTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EntityTemplate : EntityTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("The name of my entity is ");
            
            #line 4 "C:\Users\Jack\repo\CodeGenerator\Generator.Cli\Templates\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("\r\nAnd the attributes are:\r\n");
            
            #line 6 "C:\Users\Jack\repo\CodeGenerator\Generator.Cli\Templates\EntityTemplate.tt"

	foreach (var attribute in Model.Attributes)
	{

            
            #line default
            #line hidden
            this.Write("\tName: ");
            
            #line 10 "C:\Users\Jack\repo\CodeGenerator\Generator.Cli\Templates\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Name));
            
            #line default
            #line hidden
            this.Write(", Type: ");
            
            #line 10 "C:\Users\Jack\repo\CodeGenerator\Generator.Cli\Templates\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.GetType().Name));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 11 "C:\Users\Jack\repo\CodeGenerator\Generator.Cli\Templates\EntityTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 15 "C:\Users\Jack\repo\CodeGenerator\Generator.Cli\Templates\EntityTemplate.tt"

	public override string OutputPath => $"Models/{Model.Name}.cs";

	public EntityTemplate(IEnumerable<Entity> entities) : base(entities)
	{
	}

        
        #line default
        #line hidden
    }
    
}
