// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator.Cli.Templates
{
    using System.Text;
    using System.Collections.Generic;
    using Generator.Cli.Core;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Jack\repo\CodeGenerator\Generator.Cli\Templates\Helpers.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class Helpers : AbstractSingleTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("This is a simple helper file. There is only one of these.\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 6 "C:\Users\Jack\repo\CodeGenerator\Generator.Cli\Templates\Helpers.tt"

	public override string OutputPath => "Helpers.cs";

        
        #line default
        #line hidden
    }
    
}
