// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Generator.ProtectedSample.Templates
{
    using System.Collections.Generic;
    using Generator.ProtectedRegions;
    using Generator.ProtectedSample.Metamodel;
    using Generator.Core.Templates;
    using Generator.Comments;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Jack\repo\CodeGenerator\Generator.ProtectedSample\Templates\StudentPage.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class StudentPage : AbstractTemplate<Page>
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<html>\r\n<head>\r\n    ");
            
            #line 9 "C:\Users\Jack\repo\CodeGenerator\Generator.ProtectedSample\Templates\StudentPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.StartProtected($"Customise Title Here", CommentType.Xml)));
            
            #line default
            #line hidden
            this.Write("\r\n    <title>");
            
            #line 10 "C:\Users\Jack\repo\CodeGenerator\Generator.ProtectedSample\Templates\StudentPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.StudentName));
            
            #line default
            #line hidden
            this.Write("</title>\r\n    ");
            
            #line 11 "C:\Users\Jack\repo\CodeGenerator\Generator.ProtectedSample\Templates\StudentPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EndProtected()));
            
            #line default
            #line hidden
            this.Write("\r\n</head>\r\n\r\n<body>\r\n    This is the home page for ");
            
            #line 15 "C:\Users\Jack\repo\CodeGenerator\Generator.ProtectedSample\Templates\StudentPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.StudentName));
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 16 "C:\Users\Jack\repo\CodeGenerator\Generator.ProtectedSample\Templates\StudentPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.StartProtected($"Write content for {Model.StudentName} here", CommentType.Xml)));
            
            #line default
            #line hidden
            this.Write("\r\n    ");
            
            #line 17 "C:\Users\Jack\repo\CodeGenerator\Generator.ProtectedSample\Templates\StudentPage.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.EndProtected()));
            
            #line default
            #line hidden
            this.Write("\r\n</body>\r\n</html>\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 20 "C:\Users\Jack\repo\CodeGenerator\Generator.ProtectedSample\Templates\StudentPage.tt"

	private readonly IEnumerable<Page> _pages;

	public StudentPage(IEnumerable<Page> pages)
	{
		_pages = pages;
	}

	public override string OutputPath => $"{Model.StudentName}.html";
	public override IEnumerable<Page> MapObjects()
	{
		return _pages;
	}

        
        #line default
        #line hidden
    }
    
}
